CREATE USER IF NOT EXISTS 'user'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON excel_db.* TO 'user'@'%';
GRANT FILE, SUPER, SYSTEM_VARIABLES_ADMIN ON *.* TO 'user'@'%';
FLUSH PRIVILEGES;
SET GLOBAL local_infile=1;